#!/bin/bash
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-07T22:47:43" git commit --amend --date="2022-05-07T22:47:43" && git rebase --continue ;done

for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-06T22:47:43" git commit --amend --date="2022-05-06T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-05T22:47:43" git commit --amend --date="2022-05-05T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-04T22:47:43" git commit --amend --date="2022-05-04T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-03T22:47:43" git commit --amend --date="2022-05-03T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-02T22:47:43" git commit --amend --date="2022-05-02T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-05-01T22:47:43" git commit --amend --date="2022-05-01T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-30T22:47:43" git commit --amend --date="2022-04-30T22:47:43" && git rebase --continue ;done

for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-29T22:47:43" git commit --amend --date="2022-04-29T22:47:43" && git rebase --continue ;done

for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-28T22:47:43" git commit --amend --date="2022-04-28T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-27T22:47:43" git commit --amend --date="2022-04-27T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-26T22:47:43" git commit --amend --date="2022-04-26T22:47:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-25T23:33:08" git commit --amend --date="2022-04-25T23:33:08" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-24T23:33:08" git commit --amend --date="2022-04-24T23:33:08" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-23T23:33:08" git commit --amend --date="2022-04-23T23:33:08" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-22T23:33:08" git commit --amend --date="2022-04-22T23:33:08" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-21T23:33:08" git commit --amend --date="2022-04-21T23:33:08" && git rebase --continue ;done

for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-20T21:36:43" git commit --amend --date="2022-04-20T21:36:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-19T21:36:43" git commit --amend --date="2022-04-19T21:36:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-18T21:36:43" git commit --amend --date="2022-04-18T21:36:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-17T21:36:43" git commit --amend --date="2022-04-17T21:36:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-16T21:36:43" git commit --amend --date="2022-04-16T21:36:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-15T21:36:43" git commit --amend --date="2022-04-15T21:36:43" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-14T21:36:43" git commit --amend --date="2022-04-14T21:36:43" && git rebase --continue ;done

for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-13T21:44:55" git commit --amend --date="2022-04-13T21:44:55" && git rebase --continue ;done

for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-12T21:44:55" git commit --amend --date="2022-04-12T21:44:55" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-11T21:44:55" git commit --amend --date="2022-04-11T21:44:55" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-10T21:44:55" git commit --amend --date="2022-04-10T21:44:55" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-09T21:44:55" git commit --amend --date="2022-04-09T21:44:55" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-08T21:44:55" git commit --amend --date="2022-04-08T21:44:55" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-07T21:44:55" git commit --amend --date="2022-04-07T21:44:55" && git rebase --continue ;done
for a  in {1..$((RANDOM%19+3))};do GIT_COMMITTER_DATE="2022-04-06T21:44:55" git commit --amend --date="2022-04-06T21:44:55" && git rebase --continue ;done
